### ISSUE TITLE
Subsets can be used in declarations and are ordered

### ISSUE THREAD

**Issue by universal** [christophe-gouel/GAMS-Cheat-Sheet#1]
I stumbled across the following sentence in the cheat-sheet: `Subsets present the following restrictions: it is not possible to declare
variables defined on subsets; and they are not ordered, even if their parent
sets are.`

I either understand it wrongly, but for me it is possible to define parameters/variables on subsets and they are ordered if the parent set is ordered. What is not possible is to define parameters / variables on dynamic / assigned sets.

```
sets
 a /1*100/
 b(a) /50*100/
 dynamic(a)
;

dynamic(a)$(mod(ord(a), 9) = 0) = YES;

parameters
 c(a)
 d(b)
;

c(a) = ord(a);
d(b) = ord(b);

display c, d;

variables
 e(b)
* it is not possible to use the dynamically assigned set(!)
* f(dynamic)
;

e.l(b) = ord(b);
```

**Comment by christophe-gouel** [comment]
Indeed, my mistake. The cheat sheet has been updated. Thank you!
